export const data = [
    {
      id: 1,
      type: "Bungalow",
      img: "/images/about1.jpg",
      name: "Xclusive Lodge",
      price: "100k/month",
      location: "Ikeja, Lagos",
      agent: "Portablex",
    },
    {
      id: 2,
      type: "Hotels",
      img: "/images/about2.jpg",
      name: "Xclusive Lodge",
      price: "100k/month",
      location: "Ikeja, Lagos",
      agent: "Portablex",
    },
    {
      id: 3,
      type: "skyscraper",
      img: "/images/historyImage.jpg",
      name: "Xclusive Lodge",
      price: "100k/month",
      location: "Ikeja, Lagos",
      agent: "Portablex",
    },
    {
      id: 4,
      type: "Flats",
      img: "/images/about2.jpg",
      name: "Xclusive Lodge",
      price: "100k/month",
      location: "Ikeja, Lagos",
      agent: "Portablex",
    },
    {
      id: 5,
      type: "skyscraper",
      img: "/images/about1.jpg",
      name: "Xclusive Lodge",
      price: "100k/month",
      location: "Ikeja, Lagos",
      agent: "Portablex",
    },
    {
      id: 6,
      type: "Flats",
      img: "/hero.png",
      name: "Xclusive Lodge",
      price: "100k/month",
      location: "Ikeja, Lagos",
      agent: "Portablex",
    },
    {
      id: 7,
      type: "Duplex",
      img: "/type.png",
      name: "Xclusive Lodge",
      price: "100k/month",
      location: "Ikeja, Lagos",
      agent: "Portablex",
    },
    {
      id: 8,
      type: "Hotels",
      img: "/images/about2.jpg",
      name: "Xclusive Lodge",
      price: "100k/month",
      location: "Ikeja, Lagos",
      agent: "Portablex",
    },
    {
      id: 9,
      type: "Bungalow",
      img: "/images/about2.jpg",
      name: "Xclusive Lodge",
      price: "100k/month",
      location: "Ikeja, Lagos",
      agent: "Portablex",
    },
    {
      id: 10,
      type: "Duplex",
      img: "/type.png",
      name: "Xclusive Lodge",
      price: "100k/month",
      location: "Ikeja, Lagos",
      agent: "Portablex",
    },
    {
      id: 11,
      type: "Self contain",
      img: "/images/about2.jpg",
      name: "Xclusive Lodge",
      price: "100k/month",
      location: "Ikeja, Lagos",
      agent: "Portablex",
    },
    {
      id: 12,
      type: "Self contain",
      img: "/hero.png",
      name: "Xclusive Lodge",
      price: "100k/month",
      location: "Ikeja, Lagos",
      agent: "Portablex",
    },
  ];
  