export const gridCardsData = [
    {
      image: "/images/tipsBlog.png",
      type: 'Appartment',
      location: 'Lekki, Lagos',
      name: '3 BEDROOM CABIN',
      price: '$2800/month',
      view: '/details/1',
      extraClass: 'w-[250px]',
    },
    {
      image: "/images/tipsBlog.png",
      type: 'Appartment',
      location: 'Lekki, Lagos',
      name: '3 BEDROOM CABIN',
      price: '$2800/month',
      view: '/details/1',
      extraClass: 'w-[250px]',
    },
    {
      image: "/images/tipsBlog.png",
      type: 'Appartment',
      location: 'Lekki, Lagos',
      name: '3 BEDROOM CABIN',
      price: '$2800/month',
      view: '/details/1',
      extraClass: 'w-[250px]',
    },
    {
      image: "/images/tipsBlog.png",
      type: 'Appartment',
      location: 'Lekki, Lagos',
      name: '3 BEDROOM CABIN',
      price: '$2800/month',
      view: '/details/1',
      extraClass: 'w-[250px]',
    },
    {
      image: "/images/tipsBlog.png",
      type: 'Appartment',
      location: 'Lekki, Lagos',
      name: '3 BEDROOM CABIN',
      price: '$2800/month',
      view: '/details/1',
      extraClass: 'w-[250px]',
    },
  ];